var arrTZCountries=[
["US","Estados Unidos"],
["CA","Canadá"],
["GB","Reino Unido"],
["AU","Austrália"],
["DE","Alemanha"],
["FR","França"],
["DK","Dinamarca"],
["IT","Itália"],
["ES","Espanha"],
["SE","Suécia"],
["PT","Portugal"],
["RU","Rússia"],
["FI","Finlândia"],
["GR","Grécia"],
["TR","Turquia"],
["UA","Ucrânia"],
["PL","Polônia"],
["JP","Japão"],
["KR","Coreia"],
["CN","China"],
["TW","Taiwan"],
["IL","Israel"],
["IN","Índia"],
["BR","Brasil"],
["MX","México"],
["AR","Argentina"]
];
var arrWorldclock=[
["Fernando de Noronha","BR","America/Noronha",false],
["São Paulo","BR","America/Sao_Paulo",true],
["Rio de Janeiro","BR","America/Sao_Paulo",true],
["Curitiba","BR","America/Sao_Paulo",true],
["Manaus","BR","America/Manaus",true],
["Rio Branco","BR","America/Rio_Branco",true],
["Lisboa","PT","Europe/Lisbon",true],
["Madeira","PT","Atlantic/Madeira",false],
["Os Açores","PT","Atlantic/Azores",true],
["Nova Iorque","US","America/New_York",true],
["Chicago, Illinois","US","America/Chicago",false],
["Denver, Colorado","US","America/Denver",false],
["Los Angeles, Califórnia","US","America/Los_Angeles",false],
["Phoenix, Arizona","US","America/Phoenix",false],
["Anchorage, Alaska","US","America/Anchorage",false],
["Adak, Alaska","US","America/Adak",false],
["Honolulu, Havaí","US","Pacific/Honolulu",false],
["Londres","GB","Europe/London",true],
["Sydney","AU","Australia/Sydney",true],
["Toronto","CA","America/Toronto",true],
["Tóquio","JP","Asia/Tokyo",true],
["Berlim","DE","Europe/Berlin",true],
["Zurique","DE","Europe/Zurich",false],
["Paris","FR","Europe/Paris",false],
["Copenhague","DK","Europe/Copenhagen",false],
["Roma","IT","Europe/Rome",false],
["Madri","ES","Europe/Madrid",false],
["Ceuta, África","ES","Africa/Ceuta",false],
["Ilhas Canárias","ES","Atlantic/Canary",false],
["Estocolmo","SE","Europe/Stockholm",false],
["Kaliningrad","RU","Europe/Kaliningrad",false],
["Moscou","RU","Europe/Moscow",false],
["Samara","RU","Europe/Samara",false],
["Yekaterinburg","RU","Asia/Yekaterinburg",false],
["Omsk","RU","Asia/Omsk",false],
["Novosibirsk","RU","Asia/Novosibirsk",false],
["Irkutsk","RU","Asia/Irkutsk",false],
["Chita","RU","Asia/Chita",false],
["Vladivostok","RU","Asia/Vladivostok",false],
["Magadan","RU","Asia/Magadan",false],
["Petropavlovsk-Kamchatsky","RU","Asia/Kamchatka",false],
["Helsinque","FI","Europe/Helsinki",false],
["Atenas","GR","Europe/Athens",false],
["Istambul","TR","Europe/Istanbul",false],
["Kiev","UA","Europe/Kiev",false],
["Varsóvia","PL","Europe/Warsaw",false],
["Seul","KR","Asia/Seoul",false],
["Xangai","CN","Asia/Shanghai",false],
["Urumqi","CN","Asia/Urumqi",false],
["Taipei","TW","Asia/Taipei",false],
["Jerusalém","IL","Asia/Jerusalem",false],
["N. Délhi","IN","Asia/Kolkata",false],
["Calcutá","IN","Asia/Kolkata",false],
["Cidade do México","MX","America/Mexico_City",false],
["Buenos Aires","AR","America/Argentina/Buenos_Aires",false]
];
